<?php

namespace ContainerJio5yMR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiHistoryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiHistoryController' shared autowired service.
     *
     * @return \App\Controller\ApiHistoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ApiHistoryController.php';

        $container->services['App\\Controller\\ApiHistoryController'] = $instance = new \App\Controller\ApiHistoryController(($container->privates['App\\Service\\HistoryManager'] ?? $container->load('getHistoryManagerService')));

        $instance->setContainer(($container->privates['.service_locator.9X1PsB4'] ?? $container->load('get_ServiceLocator_9X1PsB4Service'))->withContext('App\\Controller\\ApiHistoryController', $container));

        return $instance;
    }
}
