<?php

namespace ContainerJio5yMR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoryCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\HistoryCommand' shared autowired service.
     *
     * @return \App\Command\HistoryCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/HistoryCommand.php';

        $container->privates['App\\Command\\HistoryCommand'] = $instance = new \App\Command\HistoryCommand(NULL, ($container->privates['App\\Service\\HistoryManager'] ?? $container->load('getHistoryManagerService')));

        $instance->setName('save-histories');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
