<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_histories' => [[], ['_controller' => 'App\\Controller\\ApiHistoryController::fetchHistories'], [], [['text', '/api/histries']], [], [], []],
    'history' => [[], ['_controller' => 'App\\Controller\\HistoryController::index'], [], [['text', '/']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
