<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~app.js',
                '/build/app.js',
                '/build/history/history.js',
            ],
            'css' => [
                '/build/app.css',
                '/build/history/history.css',
            ],
        ],
    ],
],

]];
